import { ItemStatic } from "../../Types";

export const accessory_content: Record<string, ItemStatic> = {
  "Staff Head": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1000,
    category: "weapon accessory",
    effect: [
      "A special ornament at the top of the staff mage's staff can provide extra focus. The staff head gives a +1 to Casting.",
    ],
    bulk: false,
    slot: 3,
    max_durability: 4,
  },
  "Eternal Quiver": {
    roll: [],
    quality: ["Imp 1"],
    rarity: "artifact",
    cost: 1000,
    category: "weapon accessory",
    effect: [
      "Once a day and at the cost of d4 temporary corruption, you can double the bulk size of one projectile.",
      "You can understand and speak elvish.",
    ],
    bulk: false,
    slot: 3,
    max_durability: 4,
  },
  "The Haganor Skin": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 133700,
    category: "armor accessory",
    effect: [
      "Increases armor roll by 4",
      "As an active and at the cost of 1 corruption. Succeding a [Persuasive < Resolute] test, the wearer can captivate nearby enemies with their voice. Affected enemies within earshot will lose one action, either immediately if they haven't acted yet, or on their next turn.",
      "As an active and at the cost of d4 corruption. With a successful [Persuasive\u2190Resolute] test, the wearer may assume control of a creature. The control is maintained until the master fails a [Persuasive\u2190Resolute] test (rolled on the master's initiative) or until concentration is lost [Resolute < damage]. The controlled being has only one action/turn and cannot use Active abilities or powers while being controlled.",
    ],
    bulk: false,
    slot: 3,
    max_durability: 4,
  },
  "Ormol's Wyrmcape": {
    roll: [],
    quality: ["Imp 1"],
    rarity: "unique",
    cost: 133700,
    category: "armor accessory",
    effect: [
      "+2 Discreet Modifier",
      "As an active and at the cost of d4 corruption. The player can complete an action unnoticed without rolling a sneaking check.",
      "Wearing the cape gives you free access to all entrances of Oromal's Temple.",
      "You can understand and speak with all types of Wyrms.",
    ],
    bulk: false,
    slot: 3,
    max_durability: 4,
  },
  "Agani's Coronet": {
    roll: [],
    quality: ["Imp 1"],
    rarity: "unique",
    cost: 133700,
    category: "armor accessory",
    effect: [
      "+2 Persuasive Modifier",
      "Ambrians of a clearly lower social rank will obey a direct order without requiring a Persuasive check.",
      "As an active and at the cost of d4 corruption. You can remove d4 temporary corruption from another creature. ",
    ],
    bulk: false,
    slot: 3,
    max_durability: 4,
  },
  "Wraith Legion's Crown": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 147800,
    category: "armor accessory",
    effect: [
      "+2 Resolute Modifier",
      "Reaction: Upon falling unconscious, the wearer gains d4 temporary corruption, and a wraith, possessing the player's stats and the Spirit Form (I) ability, arises. The player continues to make death saving throws while controlling the wraith, which remains active until the player regains consciousness, the wraith's health is depleted, or the battle concludes.",
    ],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
};
