import { ItemStatic } from "../../Types";

export const adventuring_gear_content: Record<string, ItemStatic> = {
  Hammer: {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 100,
    category: "adventuring gear",
    effect: [],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Mining Pick": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 50,
    category: "adventuring gear",
    effect: [],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  Scythe: {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 100,
    category: "adventuring gear",
    effect: [],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  Shovel: {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 30,
    category: "adventuring gear",
    effect: [],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  Sledgehammer: {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 100,
    category: "adventuring gear",
    effect: [],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Rope ladder": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 50,
    category: "adventuring gear",
    effect: [],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Bear trap": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 50,
    category: "adventuring gear",
    effect: [],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  Torch: {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 10,
    category: "adventuring gear",
    effect: [],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  Oil: {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 10,
    category: "adventuring gear",
    effect: [],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Flint and steel": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 10,
    category: "adventuring gear",
    effect: [],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  Rope: {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 10,
    category: "adventuring gear",
    effect: [],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
};
