import { ItemStatic } from "../../Types";

export const ammunition_content: Record<string, ItemStatic> = {
  Arrow: {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 10,
    category: "projectile",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 0,
  },
  "Precision Arrow": {
    roll: [],
    quality: ["Precise"],
    rarity: "quality",
    cost: 50,
    category: "projectile",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 0,
  },
  "Flame Arrow Weak": {
    roll: [],
    quality: ["Flaming"],
    rarity: "normal",
    cost: 50,
    category: "projectile",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 0,
  },
  "Flame Arrow Moderate": {
    roll: [],
    quality: ["Flaming"],
    rarity: "quality",
    cost: 50,
    category: "projectile",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 0,
  },
  "Flame Arrow Strong": {
    roll: [],
    quality: ["Flaming"],
    rarity: "mystical",
    cost: 50,
    category: "projectile",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 0,
  },
  "Snaring Arrow": {
    roll: [],
    quality: ["Snaring", "Special"],
    rarity: "quality",
    cost: 50,
    category: "projectile",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 0,
  },
  "Hammer Head": {
    roll: [],
    quality: ["Stun", "Special"],
    rarity: "quality",
    cost: 50,
    category: "projectile",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 0,
  },
  "Armor-piercing Head": {
    roll: [],
    quality: ["Impact"],
    rarity: "quality",
    cost: 50,
    category: "projectile",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 0,
  },
  "Rope Cutter": {
    roll: [],
    quality: ["Cut", "Special"],
    rarity: "quality",
    cost: 50,
    category: "projectile",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 0,
  },
  "Swallow's Tail": {
    roll: [],
    quality: ["Blood-letting"],
    rarity: "quality",
    cost: 50,
    category: "projectile",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 0,
  },
  Whistler: {
    roll: [],
    quality: ["Whistle", "Special"],
    rarity: "quality",
    cost: 50,
    category: "projectile",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 0,
  },
  "Grappling Hook": {
    roll: [],
    quality: ["Grapple", "Special"],
    rarity: "quality",
    cost: 50,
    category: "projectile",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 0,
  },
};
