import { ItemStatic } from "../../Types";

export const armor_content: Record<string, ItemStatic> = {
  "Natural Armor": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 0,
      },
    ],
    quality: ["Imp 0"],
    rarity: "normal",
    cost: 0,
    category: "natural armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 0,
  },
  "Light Armor": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 4,
      },
    ],
    quality: ["Imp 2"],
    rarity: "normal",
    cost: 200,
    category: "light armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Medium Armor": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 6,
      },
    ],
    quality: ["Imp 3"],
    rarity: "normal",
    cost: 500,
    category: "medium armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  "Heavy Armor": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 8,
      },
    ],
    quality: ["Imp 4"],
    rarity: "normal",
    cost: 1000,
    category: "heavy armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Woven Silk": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 4,
      },
    ],
    quality: ["Imp 0", "Flexible"],
    rarity: "normal",
    cost: 1000,
    category: "light armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Witch Gown": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 4,
      },
    ],
    quality: ["Imp 0", "Flexible"],
    rarity: "normal",
    cost: 1000,
    category: "light armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Studded Leather": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 4,
      },
    ],
    quality: ["Imp 2", "Reinforced"],
    rarity: "normal",
    cost: 1000,
    category: "light armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Order Cloak": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 4,
      },
    ],
    quality: ["Imp 0", "Flexible"],
    rarity: "normal",
    cost: 1000,
    category: "light armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Skald's Cuirass": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 4,
      },
    ],
    quality: ["Imp 0", "Reinforced", "Flexible"],
    rarity: "quality",
    cost: 5000,
    category: "light armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Wolf Skin": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 4,
      },
    ],
    quality: ["Imp 3", "Cumbersome"],
    rarity: "normal",
    cost: 100,
    category: "light armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Concealed Armor": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 4,
      },
    ],
    quality: ["Imp 0", "Concealed", "Flexible"],
    rarity: "quality",
    cost: 5000,
    category: "light armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Blessed Robe": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 4,
      },
    ],
    quality: ["Imp 0", "Flexible"],
    rarity: "normal",
    cost: 1000,
    category: "light armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Double Chain Mail": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 6,
      },
    ],
    quality: ["Imp 1", "Reinforced", "Flexible"],
    rarity: "mystical",
    cost: 12500,
    category: "light armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  "Crow Armor": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 6,
      },
    ],
    quality: ["Imp 4", "Cumbersome"],
    rarity: "normal",
    cost: 200,
    category: "medium armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  "Lacquered Silk Cuirass": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 6,
      },
    ],
    quality: ["Imp 1", "Flexible"],
    rarity: "quality",
    cost: 2500,
    category: "medium armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  "Laminated Armor": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 6,
      },
    ],
    quality: ["Imp 3", "Reinforced"],
    rarity: "quality",
    cost: 2500,
    category: "medium armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  "Field Armor": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 8,
      },
    ],
    quality: ["Imp 4", "Reinforced"],
    rarity: "quality",
    cost: 5000,
    category: "heavy armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Full Plate": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 8,
      },
    ],
    quality: ["Imp 2", "Flexible"],
    rarity: "quality",
    cost: 5000,
    category: "heavy armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Field Armor of the Pansars": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 8,
      },
    ],
    quality: ["Imp 2", "Reinforced", "Flexible"],
    rarity: "artifact",
    cost: 25000,
    category: "heavy armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Templar Full Plate": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 8,
      },
    ],
    quality: ["Imp 4", "Hallowed"],
    rarity: "mystical",
    cost: 10000,
    category: "heavy armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Wrath Armor": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 8,
      },
    ],
    quality: ["Imp 4", "Retributive"],
    rarity: "mystical",
    cost: 10000,
    category: "heavy armor",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Emberveil Mantle": {
    roll: [
      {
        source: "base",
        type: "armor",
        value: 4,
      },
    ],
    quality: ["Imp 0", "Reinforced", "Flexible"],
    rarity: "unique",
    cost: 10000,
    category: "light armor",
    effect: [
      "Once per day, you can sacrifice half your HP to replenish all temporary corruption.",
      "Wearing the armor gives you access to the spell 'Fire Soul' at novice level. This spell can't be upgraded and doesn't cost XP.",
    ],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
};
