import { ItemStatic } from "../../Types";

export const crafting_materials_content: Record<string, ItemStatic> = {
  "Night Cap": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 30,
    category: "alchemy crafting material",
    effect: [],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Iron Fragment": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 300,
    category: "blacksmith crafting material",
    effect: [],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Corrupted Blood": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1500,
    category: "ritual crafting material",
    effect: [],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Relic Shard": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 600,
    category: "artifact crafting material",
    effect: [],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Flame Oak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 30,
    category: "siege expert crafting material",
    effect: [],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Darkland Yield": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 10,
    category: "bushcraft crafting material",
    effect: [],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Primal Venom": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 30,
    category: "poisoner crafting material",
    effect: [],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
};
