import { ItemStatic } from "../../Types";

export const elixirs_content: Record<string, ItemStatic> = {
  "Homing Arrow Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "The alchemist marinates an arrow in homing essences, thereby creating an arrow that flies past other combatants and obsticals, i.e. it does not require clear line of sight. However, the archer must know the location of the target and must roll a normal attack but add +1 to the test. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Homing Arrow Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "The alchemist marinates an arrow in homing essences, thereby creating an arrow that flies past other combatants and obsticals, i.e. it does not require clear line of sight. However, the archer must know the location of the target and must roll a normal attack but add +2 to the test. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Homing Arrow Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "The alchemist marinates an arrow in homing essences, thereby creating an arrow that flies past other combatants and obsticals, i.e. it does not require clear line of sight. However, the archer must know the location of the target and must roll a normal attack but add +3 to the test. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Twilight Tincture Weak": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 1200,
    category: "elixir",
    effect: [
      "temporarily made an undead body come to life: the skin regained its redness, the body temperature rose, and the smell of the breath improved dramatically. The effect lasts for d6 days. On thoroughly corrupt creatures the effect only lasts 1 day per dose, no test is made. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Twilight Tincture Moderate": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 1400,
    category: "elixir",
    effect: [
      "temporarily made an undead body come to life: the skin regained its redness, the body temperature rose, and the smell of the breath improved dramatically. The effect lasts for d6 days. On thoroughly corrupt creatures the effect only lasts for 2 day per dose. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Twilight Tincture Strong": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1600,
    category: "elixir",
    effect: [
      "temporarily made an undead body come to life: the skin regained its redness, the body temperature rose, and the smell of the breath improved dramatically. The effect lasts for d8 days. On thoroughly corrupt creatures the effect only lasts for 3 days per dose. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Revealing Light Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "A wax candle that when lit makes living creatures (not undead or abominations) glow softly in the dark, making it harder to stay hidden. This affects everyone in the room or the vicinity, and gives +1 when trying to detect both creatures and object trying to hide or sneake.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Revealing Light Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "A wax candle that when lit makes living creatures (not undead or abominations) glow softly in the dark, making it harder to stay hidden. This affects everyone in the room or the vicinity, and gives +2 when trying to detect both creatures and object trying to hide or sneake.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Revealing Light Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "A wax candle that when lit makes living creatures (not undead or abominations) glow softly in the dark, making it harder to stay hidden. This affects everyone in the room or the vicinity, and gives +3 when trying to detect both creatures and object trying to hide or sneake.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Ghost Candle Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "The fumes from this candle will be drawn towards hidden objects/entrances and location. The candle will have effect in a radius of 1 room from the candle and leave a visible trace towards the area.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Ghost Candle Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "The fumes from this candle will be drawn towards hidden objects/entrances and location. The candle will have effect in a radius of 2 rooms from the candle and leave a visible trace towards the area.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Ghost Candle Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "The fumes from this candle will be drawn towards hidden objects/entrances and location. The candle will have effect in a radius of 3 rooms from the candle and leave a visible trace towards the area.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Fire Dye Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "Fire dye consists of salts that change the color of any fire they are cast into. If the colors are ascribed a specific meaning known to the user and an allied observer it can be used for signaling over long distances. They are also used for entertainment among the wealthy, and by charlatans to impress commoners. Will agive +3 to any persuasive tests around the fire.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Fire Dye Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "Fire dye consists of salts that change the color of any fire they are cast into. If the colors are ascribed a specific meaning known to the user and an allied observer it can be used for signaling over long distances. They are also used for entertainment among the wealthy, and by charlatans to impress commoners. Will agive +4 to any persuasive tests around the fire.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Fire Dye Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "Fire dye consists of salts that change the color of any fire they are cast into. If the colors are ascribed a specific meaning known to the user and an allied observer it can be used for signaling over long distances. They are also used for entertainment among the wealthy, and by charlatans to impress commoners. Will agive +5 to any persuasive tests around the fire.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Concentrated Magic Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "A dose of mystical essence, which gives a mystic +2 to Casting the next time he or she attempts to use a mystical power. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Concentrated Magic Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "A dose of mystical essence, which gives a mystic +4 to Casting the next time he or she attempts to use a mystical power. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Concentrated Magic Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "A dose of mystical essence, which gives a mystic +6 to Casting the next time he or she attempts to use a mystical power. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Drone Dew Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "Drone Dew is a liquid elixir made from drone spores, also containing accelerants. A person who ingests a dose of the elixir immediately falls asleep if he or she does not pass a -1 Strong test, and stays asleep for an hour or until suffering any damage. If the test is passed, the person is instead dazed, with the effect that he or she is limited to one action per turn and cannot use any active abilities for an hour.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Drone Dew Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "Drone Dew is a liquid elixir made from drone spores, also containing accelerants. A person who ingests a dose of the elixir immediately falls asleep if he or she does not pass a -3 Strong test, and stays asleep for an hour or until suffering any damage. If the test is passed, the person is instead dazed, with the effect that he or she is limited to one action per turn and cannot use any active abilities for an hour.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Drone Dew Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "Drone Dew is a liquid elixir made from drone spores, also containing accelerants. A person who ingests a dose of the elixir immediately falls asleep if he or she does not pass a -5 Strong test, and stays asleep for an hour or until suffering any damage. If the test is passed, the person is instead dazed, with the effect that he or she is limited to one action per turn and cannot use any active abilities for an hour.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Elemental Essence Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "When applying a dose of elemental essence, either one weapon, four throwing weapons or all the arrows/bolts in a quiver deal d4 elemental damage for the duration of the day. The alchemist must choose which element to prepare: fire, cold, acid or lightning. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Elemental Essence Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "When applying a dose of elemental essence, either one weapon, four throwing weapons or all the arrows/bolts in a quiver deal d6 elemental damage for the duration of the day. The alchemist must choose which element to prepare: fire, cold, acid or lightning. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Elemental Essence Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "When applying a dose of elemental essence, either one weapon, four throwing weapons or all the arrows/bolts in a quiver deal d8 elemental damage for the duration of the day. The alchemist must choose which element to prepare: fire, cold, acid or lightning. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Life Potion Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: ["Consuming an potion of life heal 1d6 points of Toughness."],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Life Potion Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 200,
    category: "elixir",
    effect: ["Consuming an potion of life heal 1d8 points of Toughness."],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Life Potion Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 200,
    category: "elixir",
    effect: ["Consuming an potion of life heal 1d10 points of Toughness."],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Elixir of Life Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "Consuming an Elixir of Life gives the drinker regenerative powers that heal d4 points of Toughness during d4 turns, on the character's initiative. Sadly the character also suffers 1 temporary corruption for each turn the elixir is in effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Elixir of Life Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "Consuming an Elixir of Life gives the drinker regenerative powers that heal d6 points of Toughness during d6 turns, on the character's initiative. Sadly the character also suffers 1 temporary corruption for each turn the elixir is in effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Elixir of Life Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "Consuming an Elixir of Life gives the drinker regenerative powers that heal d8 points of Toughness during d8 turns, on the character's initiative. Sadly the character also suffers 1 temporary corruption for each turn the elixir is in effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Flash Powder Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "A finely grained powder that emits a blinding light when thrown. Flash Powder is used with the novice level of the ability Pyrotechnics. A weak flash powder add +1 turns to the blinding effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Flash Powder Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "A finely grained powder that emits a blinding light when thrown. Flash Powder is used with the novice level of the ability Pyrotechnics. A weak flash powder add +2 turns to the blinding effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Flash Powder Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "A finely grained powder that emits a blinding light when thrown. Flash Powder is used with the novice level of the ability Pyrotechnics. A weak flash powder add +3 turns to the blinding effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Herbal Cure Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "An herbal cure consists of an alchemical poultice coupled with bandages. It smells vile but heals 1 point of Toughness. The herbal cure has greater effect if used by a character with the Medicus ability.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Herbal Cure Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "An herbal cure consists of an alchemical poultice coupled with bandages. It smells vile but heals 2 point of Toughness, if used with Medicus the moderate herbal cure will add +2 to the healing roll.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Herbal Cure Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "An herbal cure consists of an alchemical poultice coupled with bandages. It smells vile but heals 2 point of Toughness, if used with Medicus the moderate herbal cure will add +3 to the healing roll.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Holy Water Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "Holy water, instilled with the light of Prios, can heal wounds and sooth souls. Consuming a holy water will heal 2 points of toughness and remove 2 temporary corruption.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Holy Water Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "Holy water, instilled with the light of Prios, can heal wounds and sooth souls. Consuming a holy water will heal 3 points of toughness and remove 3 temporary corruption.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Holy Water Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "Holy water, instilled with the light of Prios, can heal wounds and sooth souls. Consuming a holy water will heal 4 points of toughness and remove 4 temporary corruption.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Protective Oil Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "The alchemical oil protects against elemental damage by providing d4 additional Armor against one of the elements for the duration of a scene. The alchemist must choose which of the elements that the oil shields against: fire, cold, acid or lightning. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Protective Oil Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "The alchemical oil protects against elemental damage by providing d6 additional Armor against one of the elements for the duration of a scene. The alchemist must choose which of the elements that the oil shields against: fire, cold, acid or lightning. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Protective Oil Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "The alchemical oil protects against elemental damage by providing d8 additional Armor against one of the elements for the duration of a scene. The alchemist must choose which of the elements that the oil shields against: fire, cold, acid or lightning. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Purple Sap Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: ["Removes d4 temporary corruption from the user's soul."],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Purple Sap Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: ["Removes d6 temporary corruption from the user's soul."],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Purple Sap Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: ["Removes d8 temporary corruption from the user's soul."],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Shadow Tint Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "This horribly sickening elixir was once used by mystics wanting to hide just how close they were to becoming thoroughly corrupt, making it a welcomed addition to all sorcerers' collections of mystical decoctions. Whomever manages to force down the sludge, distorts his or her shadow for a whole scene, making it appear as if the value in total corruption is d6 points lower. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Shadow Tint Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "This horribly sickening elixir was once used by mystics wanting to hide just how close they were to becoming thoroughly corrupt, making it a welcomed addition to all sorcerers' collections of mystical decoctions. Whomever manages to force down the sludge, distorts his or her shadow for a whole scene, making it appear as if the value in total corruption is d8 points lower. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Shadow Tint Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "This horribly sickening elixir was once used by mystics wanting to hide just how close they were to becoming thoroughly corrupt, making it a welcomed addition to all sorcerers' collections of mystical decoctions. Whomever manages to force down the sludge, distorts his or her shadow for a whole scene, making it appear as if the value in total corruption is d10 points lower. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Spirit Friend Weak": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 1000,
    category: "elixir",
    effect: [
      "The miraculous drug called Spirit Friend is cooked in a cauldron, but it is not the liquid that is bottled, but the vapors. The gray-white smoke is captured in small ceramic jars and inhaled when needed. Spirit Friend gives the user level I in the trait Spirit Form. The effect lasts for d4 turns, to the price of as many points in temporary corruption. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Spirit Friend Moderate": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 1200,
    category: "elixir",
    effect: [
      "The miraculous drug called Spirit Friend is cooked in a cauldron, but it is not the liquid that is bottled, but the vapors. The gray-white smoke is captured in small ceramic jars and inhaled when needed. Spirit Friend gives the user level II in the trait Spirit Form. The effect lasts for d4 turns, to the price of as many points in temporary corruption. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Spirit Friend Strong": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1400,
    category: "elixir",
    effect: [
      "The miraculous drug called Spirit Friend is cooked in a cauldron, but it is not the liquid that is bottled, but the vapors. The gray-white smoke is captured in small ceramic jars and inhaled when needed. Spirit Friend gives the user level III in the trait Spirit Form. The effect lasts for d4 turns, to the price of as many points in temporary corruption. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Stun Bolt Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "The alchemist covers a crossbow bolt in a fast acting muscle relaxant; anyone hit by the bolt must pass a [Strong -Damage] test or fall to the ground. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Stun Bolt Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "The alchemist covers a crossbow bolt in a fast acting muscle relaxant; anyone hit by the bolt must pass a [Strong -Damage+1] test or fall to the ground. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Stun Bolt Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "The alchemist covers a crossbow bolt in a fast acting muscle relaxant; anyone hit by the bolt must pass a [Strong -Damage+2] test or fall to the ground. A character without Alchemy can attempt to use the elixir by rolling a successful Cunning check. If the check fails, the elixir will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Thunder Ball Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "An alchemical load that is thrown and detonates amidst a sudden, loud flash, used with the master level of the ability Pyrotechnics.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Thunder Ball Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "An alchemical load that is thrown and detonates amidst a sudden, loud flash, used with the master level of the ability Pyrotechnics. The moderate thunder ball adds +2 damage to Pyrotechnics master ability",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Thunder Ball Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "An alchemical load that is thrown and detonates amidst a sudden, loud flash, used with the master level of the ability Pyrotechnics. The moderate thunder ball adds +4 damage to Pyrotechnics master ability",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "War Paint Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "Mystically charged paints can help a warrior in combat. War paint adds +1 to either Quick or Strong during an entire scene, and the warrior decides which attribute to boost when the paint is applied.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "War Paint Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "Mystically charged paints can help a warrior in combat. War paint adds +2 to either Quick or Strong during an entire scene, and the warrior decides which attribute to boost when the paint is applied.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "War Paint Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "Mystically charged paints can help a warrior in combat. War paint adds +3 to either Quick or Strong during an entire scene, and the warrior decides which attribute to boost when the paint is applied.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Wraith Dust Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "elixir",
    effect: [
      "The wraith dust forces an incorporeal being (a creature with the monstrous trait Spirit Form) to take physical form for the duration of a scene. The dust must be thrown with a [Accurate-2] test; if hit the spirit takes damage as living creatures do.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Wraith Dust Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "elixir",
    effect: [
      "The wraith dust forces an incorporeal being (a creature with the monstrous trait Spirit Form) to take physical form for the duration of a scene. The dust must be thrown with a [Accurate-1] test; if hit the spirit takes damage as living creatures do.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Wraith Dust Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "elixir",
    effect: [
      "The wraith dust forces an incorporeal being (a creature with the monstrous trait Spirit Form) to take physical form for the duration of a scene. The dust must be thrown with a [Accurate] test; if hit the spirit takes damage as living creatures do.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
};
