import { ItemStatic } from "../../Types";

export const poisons_content: Record<string, ItemStatic> = {
  "Antidote Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 100,
    category: "poison",
    effect: [
      "A weak antidote lowers the damage a poison by 4. The antidote does not affect any damage that a character has already suffered.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Antidote Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 200,
    category: "poison",
    effect: [
      "A moderate antidote lowers the damage a poison by 6. The antidote does not affect any damage that a character has already suffered.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Antidote Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 300,
    category: "poison",
    effect: [
      "A strong antidote lowers the damage a poison by 8. The antidote does not affect any damage that a character has already suffered.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Antidote Candle Weak": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 600,
    category: "poison",
    effect: [
      "When lit, this candle emits fumes that work as an antidote on all around it. A weak antidote candle affects every poisoned creature in the vicinity and reduces the damage of ongoing poisons 4.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Antidote Candle Moderate": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 900,
    category: "poison",
    effect: [
      "When lit, this candle emits fumes that work as an antidote on all around it. A moderate antidote candle affects every poisoned creature in the vicinity and reduces the damage of ongoing poisons 6.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Antidote Candle Strong": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1200,
    category: "poison",
    effect: [
      "When lit, this candle emits fumes that work as an antidote on all around it. A moderate antidote candle affects every poisoned creature in the vicinity and reduces the damage of ongoing poisons 8.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Poison Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "poison",
    effect: [
      "A weak poison deals d4 damage each turn for d4 turns. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Poison Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "poison",
    effect: [
      "A moderate poison deals d6 damage each turn for d6 turns. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Poison Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "poison",
    effect: [
      "A strong poison deals d8 damage each turn for d8 turns. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect..",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Poison Candle Weak": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 800,
    category: "poison",
    effect: [
      "A seemingly ordinary candle that emits poi- sonous fumes when lit; revealed with a passed  [Vigilant < alchemist's Discreet]. The poison is airborne and affects everyone in the room or in the  vicinity. The candle must burn for d4 turns before the poison is released, so the assassin can light it and leave the room before it takes effect. A weak poison candle deals 2 damage per turn. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Poison Candle Moderate": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 1200,
    category: "poison",
    effect: [
      "A seemingly ordinary candle that emits poi- sonous fumes when lit; revealed with a passed  [Vigilant < alchemist's Discreet]. The poison is air- borne and affects everyone in the room or in the  vicinity. The candle must burn for d4 turns before the poison is released, so the assassin can light it and leave the room before it takes effect. A weak poison candle deals 3 damage per turn. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Poison Candle Strong": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1600,
    category: "poison",
    effect: [
      "A seemingly ordinary candle that emits poi- sonous fumes when lit; revealed with a passed  [Vigilant < alchemist's Discreet]. The poison is air- borne and affects everyone in the room or in the  vicinity. The candle must burn for d4 turns before the poison is released, so the assassin can light it and leave the room before it takes effect. A weak poison candle deals 3 damage per turn. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Smoke Bomb Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "poison",
    effect: [
      "The smoke bomb is a ceramic vessel that emits dense alchemical smoke when crushed, and it is used with the adept level of the ability Pyrotechnics. The smoke fills a room or covers a group of people engaged inmelee combat.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Smoke Bomb Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "poison",
    effect: [
      "The smoke bomb is a ceramic vessel that emits dense alchemical smoke when crushed, it will give a +1 to the damage roll of the adept level of the ability Pyrotechnics. The smoke fills a room or covers a group of people engaged inmelee combat.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Smoke Bomb Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "poison",
    effect: [
      "The smoke bomb is a ceramic vessel that emits dense alchemical smoke when crushed, it will give a +2 to the damage roll of the adept level of the ability Pyrotechnics. The smoke fills a room or covers a group of people engaged inmelee combat.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Spore Bomb Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "poison",
    effect: ["The spore bomb is used together with the Strangler ability."],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Spore Bomb Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "poison",
    effect: [
      "The spore bomb is used together with the Strangler and gives a +1 to the damage roll of the ability.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Spore Bomb Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "poison",
    effect: [
      "The spore bomb is used together with the Strangler and gives a +2 to the damage roll of the ability.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Transforming Draught Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "poison",
    effect: [
      "This is a powerful mutagen which transforms the body of the user in a monstrous way. During a scene the user is twisted into a bestial half-creature and has a second chance to fail all Persuasive tests until the effect wears off. The draught gives the selected trait at levelI, to the cost of d4 temporary corruption. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Transforming Draught Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "poison",
    effect: [
      "This is a powerful mutagen which transforms the body of the user in a monstrous way. During a scene the user is twisted into a bestial half-creature and has a second chance to fail all Persuasive tests until the effect wears off. The draught gives the selected trait at levelI, to the cost of d6 temporary corruption. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Transforming Draught Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "poison",
    effect: [
      "This is a powerful mutagen which transforms the body of the user in a monstrous way. During a scene the user is twisted into a bestial half-creature and has a second chance to fail all Persuasive tests until the effect wears off. The draught gives the selected trait at levelI, to the cost of d8 temporary corruption. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Choking Spores Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "poison",
    effect: [
      "Choking Spores are produced from Davokar's lichens and mushrooms. The poison is used specifically with the Strangler ability.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Choking Spores Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "poison",
    effect: [
      "Choking Spores are produced from Davokar's lichens and mushrooms. The poison is used specifically with the Strangler ability and gives +1 damage to the damage roll.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Choking Spores Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "poison",
    effect: [
      "Choking Spores are produced from Davokar's lichens and mushrooms. The poison is used specifically with the Strangler ability and gives +2 damage to the damage roll.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Wild Chew Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "poison",
    effect: [
      "The red chewing resin called Wild Chew is a strong stimulant that makes the chewer more alert, less cautious and much more aggressive. One dose of Wild Chew moves 2 points in Discreet, Cunning and Resolute to Quick, Strong and Accurate for the rest of the day. During the upcoming scene, the user feels weak and has -2 on all attributes. With time, Wild Chew is highly addictive and severe withdrawal symptoms will occur unless the user consumes one dose each week, with the risk of permanent madness or death. No known drugs can counteract this.  A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Wild Chew Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "poison",
    effect: [
      "The red chewing resin called Wild Chew is a strong stimulant that makes the chewer more alert, less cautious and much more aggressive. One dose of Wild Chew moves 3 points in Discreet, Cunning and Resolute to Quick, Strong and Accurate for the rest of the day. During the upcoming scene, the user feels weak and has -2 on all attributes. With time, Wild Chew is highly addictive and severe withdrawal symptoms will occur unless the user consumes one dose each week, with the risk of permanent madness or death. No known drugs can counteract this. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Wild Chew Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "poison",
    effect: [
      "The red chewing resin called Wild Chew is a strong stimulant that makes the chewer more alert, less cautious and much more aggressive. One dose of Wild Chew moves 4 points in Discreet, Cunning and Resolute to Quick, Strong and Accurate for the rest of the day. During the upcoming scene, the user feels weak and has -2 on all attributes. With time, Wild Chew is highly addictive and severe withdrawal symptoms will occur unless the user consumes one dose each week, with the risk of permanent madness or death. No known drugs can counteract this. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Thorn Beasties Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "poison",
    effect: [
      "A handful of seeds are thrown to the  ground and one turn later d4 thorn beas- ties appear to serve the user. The thorn  beasties are small, vaguely humanoid creatures made of thorns; they do not speak but squeak and crack as twigs that are bent and rubbed together. The beasties live during a single scene before drying up to look like thorny witch dolls. The summoning of the thorn beasties is a clear violation of the natural order, meaning that the one using the seeds suffers d6 temporary corruption. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Thorn Beasties Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "poison",
    effect: [
      "A handful of seeds are thrown to the  ground and one turn later d6 thorn beas- ties appear to serve the user. The thorn  beasties are small, vaguely humanoid creatures made of thorns; they do not speak but squeak and crack as twigs that are bent and rubbed together. The beasties live during a single scene before drying up to look like thorny witch dolls. The summoning of the thorn beasties is a clear violation of the natural order, meaning that the one  using the seeds suffers d6 tem- porary corruption. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Thorn Beasties Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "poison",
    effect: [
      "A handful of seeds are thrown to the  ground and one turn later d8 thorn beas- ties appear to serve the user. The thorn  beasties are small, vaguely humanoid creatures made of thorns; they do not speak but squeak and crack as twigs that are bent and rubbed together. The beasties live during a single scene before drying up to look like thorny witch dolls. The summoning of the thorn beasties is a clear violation of the natural order, meaning that the one  using the seeds suffers d6 tem- porary corruption. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Homunculus Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "poison",
    effect: [
      "A seed is planted and one day later a miniature servant sprouts from the ground. The homunculus is small as a child, has no abilities and all attribute values are 5 (-5). It serves its maker loyally then withers away after a month; all it leaves behind is a pile of dirt. Creating a homunculus is a true violation of the natural order, meaning that the one using the seed suffers d6 temporary corruption.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Homunculus Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "poison",
    effect: [
      "A seed is planted and one day later a miniature servant sprouts from the ground. The homunculus is small as a child, has no abilities and all attribute values are 10 (+0). It serves its maker loyally then withers away after a month; all it leaves behind is a pile of dirt. Creating a homunculus is a true violation of the natural order, meaning that the one using the seed suffers d6 temporary corruption.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Homunculus Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "poison",
    effect: [
      "A seed is planted and one day later a miniature servant sprouts from the ground. The homunculus is small as a child, has no abilities and all attribute values are 15 (+5). It serves its maker loyally then withers away after a month; all it leaves behind is a pile of dirt. Creating a homunculus is a true violation of the natural order, meaning that the one using the seed suffers d6 temporary corruption.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Smoke Screen Weak": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "poison",
    effect: [
      "Give the character +3 to sneaking during their next turn or action. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Smoke Screen Moderate": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 400,
    category: "poison",
    effect: [
      "Give the character +4 to sneaking during their next turn or action. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Smoke Screen Strong": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 600,
    category: "poison",
    effect: [
      "Give the character +5 to sneaking during their next turn or action. A character without Poisoner can attempt to use the poison by rolling a successful Cunning check. If the check fails, the poison will be used without effect.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
};
