import { ItemStatic } from "../../Types";

export const ranged_content: Record<string, ItemStatic> = {
  Bow: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: [],
    rarity: "normal",
    cost: 500,
    category: "ranged weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  Crossbow: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: [],
    rarity: "normal",
    cost: 800,
    category: "ranged weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 10,
  },
  "Throwing Weapon": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Impact"],
    rarity: "normal",
    cost: 200,
    category: "throwing weapon",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 6,
  },
  "Throwing Spear": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: [],
    rarity: "normal",
    cost: 200,
    category: "throwing weapon",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 6,
  },
  Blowpipe: {
    roll: [],
    quality: ["Special"],
    rarity: "normal",
    cost: 200,
    category: "ranged weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 0,
  },
  Arbalest: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Impact"],
    rarity: "quality",
    cost: 4000,
    category: "ranged weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 10,
  },
  "Small Crossbow": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Concealed"],
    rarity: "quality",
    cost: 4000,
    category: "ranged weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 10,
  },
  "Repeating Crossbow": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Special", "Repeater"],
    rarity: "quality",
    cost: 4000,
    category: "ranged weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 10,
  },
  Longbow: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Precise"],
    rarity: "quality",
    cost: 2500,
    category: "ranged weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Horsema's Longbow": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Precise"],
    rarity: "quality",
    cost: 5000,
    category: "ranged weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Composite Bow": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Impact"],
    rarity: "quality",
    cost: 2500,
    category: "ranged weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  Bolas: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Tackle"],
    rarity: "quality",
    cost: 200,
    category: "throwing weapon",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 6,
  },
  "Throwing Wing": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Returning"],
    rarity: "quality",
    cost: 1000,
    category: "throwing weapon",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 6,
  },
  "Spear Sling": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Impact"],
    rarity: "quality",
    cost: 1000,
    category: "throwing weapon",
    effect: [],
    bulk: true,
    slot: 1,
    max_durability: 6,
  },
};
