import { ItemStatic } from "../../Types";

export const treasure_unique_content: Record<string, ItemStatic> = {
  "Ashiki's Twin Blades": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 157600,
    category: "treasure",
    effect: [
      "Gift of Shadows: When one of the daggers is used with the Backstab ability, the damage die is rolled twice and the best result stands.Action: Reaction Corruption: 1 per use. A Dance of Two: With both twin blades in hand, a person with Twin Attack can trigger a veritable shower of strikes, one dagger striking after the other like two siblings trying to outdo one another. The user can keep attacking a single target until one strike misses or the victim dies from its many wounds. Those who listen carefully can hear the daggers hiss with delight and competitiveness while the sibling rivalry is underway.Action: Active Corruption: d4",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Bunefer's Death Mask": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 148500,
    category: "treasure",
    effect: [
      "Eye of the Needle: The death mask helps its master find gaps in the enemy's armor. Activating the power reduces all enemies' Armor by d4 against melee attacks, for the duration of the combat scene. This only applies to the mask's master and does not count as extra damage \u2013 unarmored targets take damage as usual.Action: FreeCorruption: d4A Thousand Needles: A master with the Polearm Mastery ability can use the mask to paralyze enemies with piercing screams. All enemies hit by the master's pole weapon must pass a Resolute test or lose their next combat action (the mask's master makes the roll).Action: ReactionCorruption: 1 per scream from the mask",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Feud Crystal": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 124500,
    category: "treasure",
    effect: [
      "Enemies in the Walls: A person who binds herself to the feud crystal can list a number of enemies equal to half her Vigilant (rounded up), and use the crystal to get an idea of how far away they are. The master may add or remove enemies from the list, but the number of names can never exceed half her Vigilant. Furthermore, the enemies must be known by appearance and provided with names; designations like \u201cthe gray woman\u201d or \u201cthe one-eyed troll\u201d will suffice.The feud crystal shows the listed enemies in different degrees of focus, depending on their physical proximity; a crystal clear enemy is potentially close enough to see, but hidden, disguised, or otherwise unnoticeable. The user has two chances to pass any tests aimed at finding such a nearby enemy, whether it be Vigilant tests or to activate finding powers or abilities.A master struck by Sotorek\u2019s curse (see the power\u2019s corruption) must add another person as a named enemy, and strongly believes that everyone on the list is equally threatening. This new enemy is in addition to the Vigilant/2 number of names. The Game Master and the player must together come up with an interesting false enemy. The Game Master might also decide that it is in fact a hidden enemy, or let it turn into one over time, just to keep the player in a state of uncertainty\u2026 In any case, the player character is utterly convinced of the additional person\u2019s treacherous disposition.Action: Free Corruption: d4, and 1/20 chance of suffering Sotorek\u2019s curse on each use.Look of Vengeance: A master with the ability Sixth Sense can attack crystal clear enemies (see Enemies in the Walls) as if they were standing right in front of her, with weapons, powers, or traits. The user does not need to find or see the enemy to make the attack, which is performed and defended against as usual.Action: Active Corruption: d4, and 1/10 chance of suffering Sotorek\u2019s curse",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Girakosh's Steel Circle": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 133500,
    category: "treasure",
    effect: [
      "Return: The thrown steel circle returns to the master\u2019s hand, whether or not it hits its intended target. If the master is capable of throwing multiple steels per turn, the throwing steel can be used as many times as necessary.Action: Free Corruption: None Steel Rain: A master with the Steel Throw ability can send the steel circle whirling across the battlefield, zigzagging between allies in search of enemy flesh. The power turns the attack into a chain of attacks (see page 130 in the Core Rulebook for an explanation of the term Chain) against enemies in view of the master. The steel returns to its master\u2019s hand after the attack. Action: Active Corruption: d4",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "The Living Chain of Hogarz": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 108300,
    category: "treasure",
    effect: [
      "Chain Trap: A person who has bound the chain to herself can place it on the ground and trigger it as a fettering trap when someone passes over it. The master of the chain decides whether the trap is triggered and, if there are multiple creatures passing it, which creature is trapped. The victim must pass a [Quick \u20138] test or be caught, rendering them unable to move or attack in any way. Attacks against the captive are made with Advantage. Breaking free from the chain requires a successful [Strong \u20138] test; one attempt per turn, where each level of Robust adds +2 to Strong.The chain covers a 3 meter wide passage and can reach an equal height. In the hands of someone with Trapper the chain can catch two enemies who pass it, one after the other or both at once.Action: Reaction, when someone passes the chain Corruption: d4 Melee Chains: A master with the Flailer ability can choose to carry the chain around and have it catch an enemy attacking the master in melee; the effect is the same as if the chain was lying on the ground.Action: Reaction, when someone attacks the master in melee Corruption: d4",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Iloona's Mirror Shield": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 165000,
    category: "treasure",
    effect: [
      "Block Magic: The master of the shield can use it to defend against magic attacks, in which case the master\u2019s Defense replaces Resolute.Action: Reaction Corruption: d4 Shield Throw: A master with the Shield Fighter ability can once per turn throw the shield as a reaction, to block magic aimed at an ally within sight, see the shield\u2019s power Block Magic.For a master with Shield Fighter at adept level or higher, the shield can also be thrown to deal damage and possibly knock down an enemy within sight. This is done as a reaction to the shield-bearer\u2019s own attack against another enemy attacked in melee (that attack is performed as well, but without the subsequent shield bash).The shield always returns to its master\u2019s hand after the throw.Action: Reaction Corruption: d6",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "The Whispering Necklace of Lapi-Esha": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 159000,
    category: "treasure",
    effect: [
      "Revealing Whisper: The necklace whispers secrets about whoever the master is looking at. The serpent lets its master know which attribute is the target\u2019s weakest (without mentioning its exact value), and what burdens (see the Advanced Player\u2019s Guide, page 56) the person has. With a successful [Vigilant\u2190Discreet] test the master also learns the value of the weakest attribute and, if the target has the burden Dark Secret, what that secret is.Action: Free Corruption: d4 Venomous Bite: The necklace can be made to attack in melee with its venomous bite. The snake attacks once per turn at the same time as its master, against the same target. If the master hits an enemy during the turn, so does the snake. The snake only attacks once per turn, no matter how many attacks the master makes.Roll d8. If the result is higher than the enemy\u2019s armor value, the snake\u2019s fangs pierce their victim; the bite itself deals no damage, but the target is afflicted by a weak poison, d4 damage for d4 turns. For masters with the Poisoner ability the serpent\u2019s poison is moderate and deals d6 damage for d6 turns.Action: Reaction, when the master attacks in melee Corruption: d4",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Nema's Orbit Statuette": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 130800,
    category: "treasure",
    effect: [
      "Dragon Dance: As long as the sun is up, the master can activate the upper part of the statue and summon a dragon fly, which serves the master faithfully for one scene (see the Core Rulebook, page 225).Action: Active Corruption: d4 Snake Dance: As long as the sun is below the horizon, the master can activate the lower part of the statue and summon a kanaran, which serves the master faithfully for one scene (see the Core Rulebook, page 223).Action: Active Corruption: d4",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "The War Horn of the Stormhowler": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 153800,
    category: "treasure",
    effect: [
      "Allies to the Rescue: The horn blast booms through the region and all allies within a day\u2019s march immediately become aware that the master is in danger. They also know where to find her. Ultimately the Game Master decides which allies are nearby (if any), who they are, and how far away they are from the master. If you want to base it on die rolls, we suggest the master must pass a Persuasive test and that the allies are d10 hours away \u2013 on 0 the master rolls d10 again, which this time indicates a number of minutes rather than hours. The allies that come to the rescue are [PC+1] in numbers with one level of resistance lower than the master, led by a person with the same resistance level as the master (for more on resistance levels, see the Symbaroum Monster Codex, page 179).Action: Free Corruption: None Storm Fright: In the hands of someone with the Dominate ability the horn can produce a horn blast so powerful that enemies might flee in fear. It takes a successful [Persuasive\u2190Resolute] test to affect an enemy, who will then flee for d6 turns.Action: Active Corruption: d6",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  Worldcleaver: {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 113000,
    category: "treasure",
    effect: [
      "Demon Birth: The master of the weapon can cleave reality instead of an enemy, and birth a daemon through the wound. The daemon obeys the wielder for one scene, before being sucked back into the world wound. The daemon has stats as an Intruder (see the Symbaroum Monster Codex, page 173). Action: Active Corruption: d6 Bloody Banishment: A master with the ability Two-handed Force can strike an enemy and cleave reality with the same attack. An enemy damaged by this attack must roll over the damage on 1d20 or be sucked into the Yonderworld. Out in the howling madness the victim takes d6\u20133 corruption per turn. A Resolute test can be made every turn, which if successful returns the victim to the world of the living. Victims who are blight born during their stay in the Yonderworld immediately return to the regular world in the form of dragouls, controlled by the master of World cleaver.Action: Reaction Corruption: d6",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Xtala's Hourglass": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 133700,
    category: "treasure",
    effect: [
      "Sands of Time: The master of the artifact can let sand run through the glass and thus stop time for a number of turns. During these turns the user may act alone, and the effect of all actions occurs when time starts moving again. Every turn the master acts outside of time she becomes a year older. Furthermore, the master must roll 1d20 each turn; if the result is equal to or less than the number of turns the master has acted outside of time during the current scene, the master falls dead to the ground. No reroll is allowed; time is relentless in its vengeance.Action: Active Corruption: d4 per turn outside of time",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Fullangra's Coffer": {
    roll: [],
    quality: [],
    rarity: "unique",
    cost: 133700,
    category: "treasure",
    effect: [
      "You can order Fullangra to do any rarity of action she always moves at Death March.",
      "Asking Fullangra to do a grim deed, will require her release, but she will attempt it.",
      "If a master releases Fullagra without asking a grim deed she will heal d6 permanent corruption or grant them 6 Lucky Coins.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  Souleater: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: [],
    rarity: "unique",
    cost: 133700,
    category: "heavy weapon",
    effect: [
      "As a reaction to dealing a killing blow, and at the cost of d4 corruption. Allows the weilder to absorb a mystical power from its victim.",
      "At the cost of d4 corruption. The master of the weapon can use the mystical power in storage as if it was his or her own. The master's Resolute counts as 15 in everything having to do with making use of that power.",
    ],
    bulk: false,
    slot: 2,
    max_durability: 10,
  },
  "Ramaran's Bane": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Long", "Impact", "Precise"],
    rarity: "unique",
    cost: 133700,
    category: "long weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 8,
  },
  "The Troll Cross of Ella": {
    roll: [],
    quality: ["Flexible"],
    rarity: "unique",
    cost: 133700,
    category: "shield",
    effect: [
      "As a reaction and at the cost of 1 corruption. The master of the cross can use Ella's ancient blessings as protection against powers affecting the mind. Each turn the carrier can gain a second chance to succeed against a power involving Resolute. If the power acts over time, the master may also make a re-roll to abort an ongoing effect.",
      "As reaction and at the cost of d4 (or d6 on failure), The master can use Ella's wisdom to turn incoming spells back at the caster. This applies to all offensive spells targeting the master. The Mirror of Vengeance acts as if the master attacked with the same power, using their Resolute attribute for success determination, possibly modified by the caster's attributes. However, failure results in additional corruption for the master.",
    ],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  Burnreaper: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Recall"],
    rarity: "unique",
    cost: 133700,
    category: "throwing weapon",
    effect: [
      "As an active ability, and at the cost of gaining d4 corruption, Burnreaper will be set aflame and ignore the target's armor on its next attack.",
      "As an active ability, and the cost of gaining d6 corruption, Burnreaper can be thrown at all visible enemies. The axe will return after the first failed attack.",
    ],
    bulk: false,
    slot: 1,
    max_durability: 10,
  },
};
