import { ItemStatic } from "../../Types";

export const treasure_mystical_content: Record<string, ItemStatic> = {
  "Tall Thin Vase": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 18900,
    category: "treasure",
    effect: [
      "Tall, thin vase of glazed porcelain, purple with a motif of bright red vines. Plants placed in the vase will not age, wither, bloom, or bear fruit.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Seashell Facial Mask": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 13000,
    category: "treasure",
    effect: [
      "Facial mask made of seashells in pink, white and light blue. Its wearer can hold their breath under water at up to ten meters\u2019 depth, for a maximum of ten minutes.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Stormy Mountain Fan": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 10100,
    category: "treasure",
    effect: [
      "Handheld fan painted with stormy mountain scenery, which actively cools the air when waved. Roll d6 when used a result of 6 inflicts d4 damage and causes facial hair to freeze.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Bronze Bell": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 16700,
    category: "treasure",
    effect: [
      "Bronze bell whose inside and clapper is engraved with cuneiform characters. If carried so that it is hanging freely, it tinkles faintly whenever there is an abomination within a hundred meter radius, but at the risk of being detected [10\u2190the creatures Vigilant].",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Pearl-Covered Notebook": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 10300,
    category: "treasure",
    effect: [
      "Notebook with thin pages of parchment and pearl-covered binding. Text written in the book is only visible to the person who wrote it.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Peeling Metal Canister": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 19400,
    category: "treasure",
    effect: [
      "Metal canister whose white color has largely peeled off. It is half full of a powder which conceals signs of aging on human skin for twenty-four hours, at the cost of d4 temporary corruption; contains enough powder for 10+d10 applications.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Slimy Stone Amulet": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 13200,
    category: "treasure",
    effect: [
      "Amulet set with a gray stone that emits a slimy secretion, which dries into an ineffective resin after a while. The secretion is enough for two individuals per scene. If applied on the skin, it has a repellent effect on insects; if the wearer succeeds with [13\u2190Resolute] the insects select other targets.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Incense Sticks": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 17600,
    category: "treasure",
    effect: [
      "Eight sticks of incense in a cylindrical leather case. Can be burned during negotiations, granting those with the Manipulator boon +2 to Persuasive tests.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Sapphire Wedding Ring": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 14600,
    category: "treasure",
    effect: [
      "Wedding ring of pure gold, adorned with six sapphires. A loving spirit is bound to the ring and can act in the wearer\u2019s defense; once per scene the wearer may reroll a failed Defense test. But the spirit is jealous and will haunt the wearer\u2019s romantic partner with horrifying nightmares.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Wooden Box with Lenses": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 18300,
    category: "treasure",
    effect: [
      "Smooth wooden box containing two frameless spectacle lenses. Makes it easier to follow tracks in the wilderness (+1 to Vigilant tests), but weakens the other senses so that the wearer becomes less aware of her surroundings (\u20133 to Vigilant tests for detecting threats).",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Cast-Iron Animal Heads": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 16300,
    category: "treasure",
    effect: [
      "Three beautiful, cast-iron animal heads each the size of a clenched fist, completely free of rust \u2013 a wolf, a bear and a wild boar. Loops underneath allow them to be tied together into a bola, which adds +3 to the success test when thrown at creatures of the Beast category.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Briar Pipe": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 16500,
    category: "treasure",
    effect: [
      "Long-stemmed briar pipe whose bowl is shaped like a woman\u2019s face with her eyes closed. Can be used when performing the Oracle ritual, with its smoke conveying the visions, granting a +3 bonus to Resolute tests.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Red Glass Lantern": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 18200,
    category: "treasure",
    effect: [
      "Lantern with red glass in a metal frame, about the size of a tankard. When lit in an otherwise dim environment, it can expose people who are trying to hide intense feelings (such as outrage, love or grief). It takes one successful Vigilant test per target to notice their seemingly glowing outlines.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Chainmail Gauntlet": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 13700,
    category: "treasure",
    effect: [
      "A simple right-handed chainmail gauntlet that needs relining. The person wearing it can never involuntarily lose her grip on the right-hand weapon.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Cuneiform Rune Ring": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 18900,
    category: "treasure",
    effect: [
      "A modest ring of low-karat gold, with cuneiform runes engraved on the inside (\u201cThe cleansing one\u201d). Its owner can conceal any skin damage for one scene per day, including scars and tattoos. These can still be detected with Witchsight and a successful Vigilant test.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Blackened Silver Key": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 17000,
    category: "treasure",
    effect: [
      "Key of blackened silver that can slide into most locks. Roll d6: on 1\u20134 the lock opens; on 5\u20136 the mechanism melts, making it impossible to unlock.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Smoke-Colored Crystal Staff": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 17600,
    category: "treasure",
    effect: [
      "Staff of smoke-colored crystal, as long as one\u2019s palm, with one end shaped like a rounded point. When pointed at the North Star it gives a faint glow, granting +3 to Orientation tests, even underground.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Small Copper Pot": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 13800,
    category: "treasure",
    effect: [
      "Small copper pot, large enough to brew one dose of a single elixir. Adding an amount of silver equal to one (1) silver thaler makes the elixir one level stronger. If it is already Strong, the effect die is increased by one step.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Scarlet Wood Knife": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 11300,
    category: "treasure",
    effect: [
      "Knife with a handle of scarlet wood and a ten centimeter curved blade, engraved with a running predator. Adds +2 to Cunning tests when harvesting a monster trophy.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Cracked Uncut Ruby": {
    roll: [],
    quality: [],
    rarity: "mystical",
    cost: 19200,
    category: "treasure",
    effect: [
      "Cracked, uncut ruby that emits enough heat to steam in cold and damp weather. If set in the hilt or grip of a one-handed weapon with the mystical quality Death Rune, the quality\u2019s effect die is increased to d10, at the cost of d4 temporary corruption per turn.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
};
