import { ItemStatic } from "../../Types";

export const treasure_normal_content: Record<string, ItemStatic> = {
  "Leather Pouch": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1500,
    category: "treasure",
    effect: [
      "Leather pouch containing stone marbles, fourteen shiny black ones and eight off-white, to play with or use as sling stones.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Ornamented Lyre": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 2000,
    category: "treasure",
    effect: [
      "Richly ornamented lyre of silver that can be fitted with new strings.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Raven Feather": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1000,
    category: "treasure",
    effect: [
      "The feather is pristine, as dark as the midnight sky. Legend has it that it bestows good fortune upon its bearer.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Wolf Head Nail File": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1500,
    category: "treasure",
    effect: [
      "Nail file with one rough side and one smooth, and a handle shaped like the silhouette of a wolf's head.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Copper Wire Paper Clips": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1400,
    category: "treasure",
    effect: [
      "Box containing twenty-four paper clips of patinated copper wire.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Model Castle Glass Bottle": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1800,
    category: "treasure",
    effect: [
      "Glass bottle containing a wooden model castle in a moorland landscape.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Simple Frying Pan": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1800,
    category: "treasure",
    effect: ["Simple frying pan of rusted iron on which nothing ever sticks"],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Bronze Measuring Cups": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1900,
    category: "treasure",
    effect: ["Set of five bronze measuring cups, all in different sizes"],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Bone Discs Box": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1100,
    category: "treasure",
    effect: [
      "Box containing thirty-six small, bone discs engraved with Symbarian cuneiform characters",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Living Vines Basket": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1100,
    category: "treasure",
    effect: [
      "Small basket woven out of miraculously living vines with healthy green leaves",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Gold Teeth Necklace": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1500,
    category: "treasure",
    effect: ["Necklace made entirely from linked gold teeth"],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Silver Wraith Owl Brooch": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1700,
    category: "treasure",
    effect: [
      "Silver brooch depicting a wraith owl, the rings around its eyes made from black, faceted stones",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Porcelain Plate": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1300,
    category: "treasure",
    effect: [
      "White-glazed and somewhat cracked porcelain plate, painted with the weathered motif of a straight-backed woman in a long dress, with a poleaxe resting against her shoulder",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Lindworm Bone Comb": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1300,
    category: "treasure",
    effect: [
      "Comb made of lindworm bone with cuneiform characters on each tooth, which not only untangles one's hair but cleans away dirt and grease",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Cracked Ceramic Platter": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1900,
    category: "treasure",
    effect: [
      "Cracked ceramic serving platter, decorated with various raritys of fruit on a white background - two of the fruits are unfamiliar to present-day gardeners",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Golden Rose Box": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1300,
    category: "treasure",
    effect: [
      "Box in the shape of a rose with twenty-four golden petals in four rows, which must be unfolded in sequence to expose its empty interior",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Silver Fountain Pen": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1100,
    category: "treasure",
    effect: [
      "Silver fountain pen with golden details, which never seems to run out of ink",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Bronze Caliper": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1400,
    category: "treasure",
    effect: [
      "Bronze caliper, marked in cuneiform with an unknown unit of measurement",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Dark Blue Ceramic Flowerpot": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1200,
    category: "treasure",
    effect: [
      "Flowerpot of dark blue ceramic, decorated with a white and red motif of daemonic couples in obscene positions",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Copper Box with Ceramic Figurines": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1400,
    category: "treasure",
    effect: [
      "Copper box containing twelve ceramic figurines, each depicting the same goblin's head, but with different facial expressions",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Patinated Copper Sheet": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1900,
    category: "treasure",
    effect: [
      "Patinated sheet of copper with cuneiform, listing the ingredients and procedure for brewing the alcoholic honey beverage Noid",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Ornamented Dagger": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1400,
    category: "treasure",
    effect: [
      "Ornamented dagger with a dull steel blade that slides into the hilt when pressed against something",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "White-Glazed Porcelain Mask": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1500,
    category: "treasure",
    effect: [
      "White-glazed porcelain mask that covers the upper part of one's face, shaped with an owl's beak, small branched horns, and red-lined eye openings",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Gold Handle Wax Stamp": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1600,
    category: "treasure",
    effect: [
      "Wax stamp with a handle of pure gold whose mark represents the royal rune Labrys",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Cracked Tallow Candle": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1300,
    category: "treasure",
    effect: [
      "Thick, cracked tallow candle which, when lit, emits a dark yellow smoke",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Green Ceramic Oil Lamp": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1600,
    category: "treasure",
    effect: [
      "Green, ceramic oil lamp with a shade of patterned glass that rotates while the lamp is lit",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Leather Eyepatch": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1600,
    category: "treasure",
    effect: [
      "Brown, leather eyepatch with different-colored gemstones arranged in the form of an open eye",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Stone Ship Model": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1300,
    category: "treasure",
    effect: [
      "Model of a twin-masted stone ship; the stern can be opened to reveal sixteen tin figures spread across two decks",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Black Leather Leash": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1500,
    category: "treasure",
    effect: [
      "Black leather leash that connects to a collar of the same material, large enough to fit around a bull's neck and decorated with studs of pure gold",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Damaged Wooden Box": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1600,
    category: "treasure",
    effect: [
      "Badly damaged wooden box with moldy fabric inside; contains five well-preserved seeds which, if handled correctly (successful Cunning with Alchemy), can grow into cherry trees with multicolored flowers and delicious fruit",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Puzzle Wooden Box": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1300,
    category: "treasure",
    effect: [
      "Long, thin wooden box full of flat copper pieces of different shapes, all of them badly patinated; a puzzle with two missing pieces; washing off the patina reveals the motif of a daemonic abomination",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Black Bone Spoon": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1800,
    category: "treasure",
    effect: [
      "Spoon of black bone, carved with runes filled with red paint that has partially worn off; nothing one eats with the spoon is absorbed by the body",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Game Board": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1900,
    category: "treasure",
    effect: [
      "12x9 game board with different-sized squares of various colors/materials (white bone, black wood, and patinated copper), in a frame of patterned hardwood",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Ettercopal Wind Chime": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 2000,
    category: "treasure",
    effect: [
      "The clappers and tubes of a wind chime made from melodious ettercopal",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Magnetic Black Stone": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1700,
    category: "treasure",
    effect: [
      "Fist-sized, irregular, glistening black stone with magnetic properties",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Chalk Case": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1200,
    category: "treasure",
    effect: [
      "Silver case with sixteen dried-up, multicolored pieces of chalk; they are unused and can be restored for drawing after successful alchemical treatment (Cunning test with Alchemy)",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Carved Bone Statue": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1900,
    category: "treasure",
    effect: [
      "Carved bone statue of an andrik with a cracked beak, armed with a crossbow and a hatchet",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Silver Tuning Fork": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1800,
    category: "treasure",
    effect: ["Silver tuning fork in the key of D"],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Green Metal Stiletto": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 2000,
    category: "treasure",
    effect: [
      "Stiletto with a wavy blade of strange green metal; the hilt is shaped as a human child with clasped hands",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Black Stone Ox Statuette": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1300,
    category: "treasure",
    effect: [
      "Statuette of an ox chiseled in black stone; raising its tail tilts the horns",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Blackened Walking Stick": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1600,
    category: "treasure",
    effect: [
      "Blackened walking stick, patterned like the scales of a snake or fish, with a fist-sized pearl for a knob",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Silver Buckle": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1300,
    category: "treasure",
    effect: [
      "Circular belt or cloak buckle made of silver, with gold details depicting three crossed arrows",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Copper Spyglass": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1700,
    category: "treasure",
    effect: [
      "Copper spyglass with rotating segments; aiming it at the sun reveals colorful patterns which change as one rotates the segments",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Crystal Hourglass": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1300,
    category: "treasure",
    effect: [
      "Hourglass of misty white crystal contained within a blue-gray metal stand, whose sand runs exactly twice as fast in one direction as it does in the other",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Silver Watering Can": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1700,
    category: "treasure",
    effect: [
      "Silver watering can whose long spout has been broken off; decorated with motifs of grotesque birds",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Mystically Preserved Ferret": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1900,
    category: "treasure",
    effect: [
      "Stuffed and mystically preserved ferret that has undergone a Symbarian rite of exaltation - equipped with predatory jaws, long claws, a crown of horns, and sickly yellow eyes",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Bone Flute": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1100,
    category: "treasure",
    effect: [
      "Bone flute, as long as one's palm and as thin as a little finger; attracts 1D20 small birds if played by someone with the Musician boon",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Pink Pearl": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 2000,
    category: "treasure",
    effect: [
      "Shimmering pink pearl with streaks of red, the size of an eyeball, with the sweet-sour taste of berry compote; never loses size or flavor",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Broken Dreamcatcher": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1700,
    category: "treasure",
    effect: [
      "The parts of a broken dreamcatcher that can be repaired (Cunning test with Blacksmith). Brings peace to the sleeping; those burdened by Nightmares have two chances to pass their Resolute test",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Clay Cruse": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1200,
    category: "treasure",
    effect: [
      "A clay cruse stoppered with a wax-sealed cork, bearing a life-sustaining seal that has kept its contents fresh for hundreds of years - red wine of excellent quality from a particularly superb vintage",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Gray Stone Statue": {
    roll: [],
    quality: [],
    rarity: "normal",
    cost: 1400,
    category: "treasure",
    effect: [
      "Statue of glossy, dark gray stone, as tall as a forearm, in the form of a daemon. The base bears a cuneiform inscription that can be interpreted by someone with Loremaster (master): \u201cJeberaja\u201d",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Lucky Coin": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 1100,
    category: "treasure",
    effect: ["By spending a Lucky Coin, the user may re-roll any dice roll."],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
};
