import { ItemStatic } from "../../Types";

export const treasure_artifact_content: Record<string, ItemStatic> = {
  "Animal Mask": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1000,
    category: "treasure",
    effect: [
      "Blood wading witches tend to identify with the beasts of the wild, a sentiment embodied by the wearing of animal masks. Every animal mask with mystical properties symbolizes an animal and gives a +1 bonus on an attribute associated with that animal - Discreet, Quick, Cunning, Strong or Vigilant.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Bark Mask": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1000,
    category: "treasure",
    effect: [
      "Green weaving witches often cover their faces with a mask of bark, as a symbol of their connection to nature. Many of these masks are infused with power and provide one re-roll per scene on a test related to plants and anything growing, for example Thorn Cloak and Entangling Vines. The re-roll may be used for tests to activate such powers or to resist the effect of such powers.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Orb of Veiled Shadow": {
    roll: [],
    quality: [],
    rarity: "quality",
    cost: 1700,
    category: "treasure",
    effect: [
      "Crushing the orb will cleanse all temporary corruption from anybody within 5 squares. The orb is then spent.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Burial Shroud": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1000,
    category: "treasure",
    effect: [
      "The spiritualists among the witches often wear a shroud over their head when contacting the spirits of the dead, since this makes the spirits calmer and allows for a deeper connection. A mystic using such an artifact gains a +1 bonus to Resolute in all tests when dealing with spirits - both when trying to control them (as in the power Tormenting Spirits) and when trying to resist the effect of monstrous traits used by spirits, involving the Resolute attribute.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Death Mask": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1000,
    category: "treasure",
    effect: [
      "The necromancers' aspiration to dominate death has led to the use of hideous death masks that have been infused with power. A death mask gives a +1 bonus on tests for all powers and rituals affecting the intersection between life and death, for instance the power Revenant Strike and the ritual Raise Undead.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Healing Spider": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 400,
    category: "treasure",
    effect: [
      "A small spider figurine which is placed on an open wound, where it quickly covers itself and the wound in a web that heals 1d12 Toughness over the course of a day. The spider cannot heal damage from poison or other internal injuries. When done, the spider creeps up from the wound to be reused on new ones. The one treated by the healing spider suffers one point in temporary corruption.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Iron Crown": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1000,
    category: "treasure",
    effect: [
      "Demonologists often wear a crown of rusty iron when tearing at the world's fabric. These crowns give a +1 bonus when manipulating the world, as with the mystical powers Exorcize and Teleport, or the ritual Summon Daemon.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Iron Pact Ring": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 0,
    category: "treasure",
    effect: [
      "The ring fully protects its carrier from corruptive surroundings, like the taint in Davokar's darkest parts or the blight transferred through bites and claws (not from mystical powers or other voluntary sources). He who has bound himself to the ring suffers d4 damage from all corruption he willingly accepts. Once during each night's sleep, he who is bound to the ring may send a dream message to someone else with a ring - they must know the person exists.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Marlit Cape": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 400,
    category: "treasure",
    effect: [
      "The skin of a marlit, a reptile known for its sneaky hunting style, is treated with preserving alchemical preparations so that it keeps its camouflaging properties after the death of the beast. The wearer has a +1 bonus to Discreet when sneaking and hiding.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Mummified Hand": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 0,
    category: "treasure",
    effect: [
      "Free d4 corruption: With a successful roll against Resolute, the owner of the amulet may once per turn reroll a success test. Active d6 corruption: Word of Doom: If the owner of the amulet masters the ability Leader he can utter words of doom over his enemWord of Doom: If the owner of the amulet masters the ability Leader he can utter words of doom over his enemies. With a successful roll against Resolute the enemy's chance of making a successful hit is reduced for the remainder of the scene \u2013 the owner may make two attempts against Defense to avoid physical attacks.ies. With a successful roll against Resolute the enemy's chance of making a successful hit is reduced for the remainder of the scene - the owner may make two attempts against Defense to avoid physical attacks.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Meeting Stone": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 200,
    category: "treasure",
    effect: [
      "A stone is loaded with an invitation to a specific person, who upon receiving and touching the artifact instinctively knows where the stone's owner is waiting. Only a mystic (with at least one mystical power) can activate a meeting stone.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Mind Prism": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1000,
    category: "treasure",
    effect: [
      "The illusionists of Ordo Magica often use a prism to describe how the perception of reality may be broken down and understood. Some of these crystals are filled with so much suggestive energies that they provide a +1 bonus to all tests related to the creation of illusions.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Mystical Focus": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1200,
    category: "treasure",
    effect: [
      "A tradition-specific focus gives a +1 bonus on all tests related to all powers of the tradition, but limited to one use per scene. The bonus may be used together with other lesser artifacts that also provide a bonus to success tests for the mystical power in question. A mystical focus is bound to the user as other, higher artifacts - that is, by spending an experience point or by willingly accepting one point in permanent corruption.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Order Medallion": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 200,
    category: "treasure",
    effect: [
      "The medallions of Ordo Magica are given to novices and stay with the wizards for their entire career. When the wizard reaches adept level, the medallion transforms to symbolize this step; the same thing happens when reaching master level. Some chapters have made the order medallion mandatory and have also bound certain functions to it, such as the ability to open doors which are closed to outsiders/novices/adepts and to activate the chapter's magic circle.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Pest Mask": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 800,
    category: "treasure",
    effect: [
      "In a world full of contagions and poisons it is no wonder that many methods - effective or only superstitious - have been developed to resist such phenomena. The Confessors of the Sun Church, for instance, carry pest masks to protect themselves. They allow the wearer to use their Resolute instead of Strong on tests to resist sicknesses and poisons.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Ritual Codex": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 400,
    category: "treasure",
    effect: [
      "A ritual is penned down in a codex so that another ritualist can perform it without having previously learned the ritual. The codex can only be used once.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Ritual Focus": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 800,
    category: "treasure",
    effect: [
      "A tradition-specific object which gives a +1 bonus on success tests for all rituals belonging to the tradition. See examples to the right. ",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Ritual Seal": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1200,
    category: "treasure",
    effect: [
      "The artifact crafter binds a ritual to a seal; when broken, the effect of the ritual is triggered. The creator of the seal need not know the ritual, but must be in the company of one who does when it is created (or have access to a ritual codex explaining the ritual; the codex is destroyed with this act). He or she who breaks the seal suffers from temporary corruption as usual.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Ruler's Ring": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1000,
    category: "treasure",
    effect: [
      "Prominent mind-warping wizards often carry a gold ring on a finger, around the wrist or upper arm, or on the head in the form of a headband. To them, this represents the noble endeavor of the ruler. These rings are often instilled with the ability to dominate all living beings. If so, the gold ring gives a +1 bonus to all test involving powers and rituals of Wizardry affecting the will of the target, for example the use of, and resistance to, Bend Will and Telepathic Interrogation.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Rune Staff": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1200,
    category: "treasure",
    effect: [
      "The hallmark of the staff mage is his or her personal staff, carved with the runes of the elements. In the hand of its owner, the staff emits a protective aura (Armor +d4), and is also the instrument through which the mage wields his or her powers.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Soul Stone Shard": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1200,
    category: "treasure",
    effect: [
      "A Soul Stone Shard is the item required to perform the ritual with the same name.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Spark Stone": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1000,
    category: "treasure",
    effect: [
      "The power of a Pyromancer is increased by this glowing amber. The spark stone is a weaker version of the renowned Sun Stones that the master pyromancers of old could craft from summoned fire spirits. Nowadays, the fire wizards have to make do with lesser artifacts, far from as powerful but still a great help to those whose skills relate to fire and burning. All powers with fire effects gain a +1 bonus to the effect die when used by someone with a spark stone in hand or on top of his or her staff.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Spell Scroll Novice": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 200,
    category: "treasure",
    effect: [
      "Artifact crafters in Ordo Magica can bind a mystical power at the novice, adept or master level (depending on the level of the artifact) to a scroll. The power may then be activated by someone else who has Wizardry at a level equal to or higher than the level of the power, or someone who has the ability Loremaster at adept level. Whoever activates the scroll suffers temporary corruption as usual and the scroll is spent upon activation.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Spell Scroll Adept": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 400,
    category: "treasure",
    effect: [
      "Artifact crafters in Ordo Magica can bind a mystical power at the novice, adept or master level (depending on the level of the artifact) to a scroll. The power may then be activated by someone else who has Wizardry at a level equal to or higher than the level of the power, or someone who has the ability Loremaster at adept level. Whoever activates the scroll suffers temporary corruption as usual and the scroll is spent upon activation.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Spell Scroll Master": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 600,
    category: "treasure",
    effect: [
      "Artifact crafters in Ordo Magica can bind a mystical power at the novice, adept or master level (depending on the level of the artifact) to a scroll. The power may then be activated by someone else who has Wizardry at a level equal to or higher than the level of the power, or someone who has the ability Loremaster at adept level. Whoever activates the scroll suffers temporary corruption as usual and the scroll is spent upon activation.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Spell Seal Novice": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 800,
    category: "treasure",
    effect: [
      "An artifact crafter has bound a mystical power at the novice or adept level (depending on the level of the artifact) to a seal; when the seal is broken, the power is activated. Whoever breaks the seal suffers temporary corruption as usual and the seal is spent when broken.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Spell Seal Adept": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1200,
    category: "treasure",
    effect: [
      "An artifact crafter has bound a mystical power at the novice or adept level (depending on the level of the artifact) to a seal; when the seal is broken, the power is activated. Whoever breaks the seal suffers temporary corruption as usual and the seal is spent when broken.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Staff Foot": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1000,
    category: "treasure",
    effect: [
      "A staff foot forged with strengthening spells can give the staff of a staff mage extra power when used as a weapon. The artifact is attached to the staff and gives a +1 bonus on the effect tests of all melee or ranged attacks, and on all powers which directly use the staff as a weapon. Even if this artifact most often is attached to a rune staff, it may be attached to an ordinary wooden staff with the same effect.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Sun Mask": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1000,
    category: "treasure",
    effect: [
      "The sun masks of the theurgs bestow spiritual warmth to the cold-hearted and spread light where no other light can reach. Worn by a theurg, they can also assist in combat against undead and abominations. The mask radiates light around the wearer as if it is a torch; also, all powers with holy or banishing effects have a +1 bonus to effect tests.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Toad Guard": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 100,
    category: "treasure",
    effect: [
      "A figurine in the form of a toad acts as an alarm. The user - who has to know at least one mystical power - whispers a triggering condition to the figurine; the trigger has to be of a physical nature and must occur close to the toad guard, for example that someone passes through the grove or the door is opened from outside. If activated, the toad will wake everyone with a loud croaking.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Transcendental Weapon": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 1200,
    category: "treasure",
    effect: [
      "These weapons were forged to allow a wielder to strike from a distance. Only mystics (defined as someone who has learned at least one mystical power) know how to use such an artifact. The attack is rolled as if in melee combat but may hit distant targets and requires a clear line of sight, just as ranged attacks. Active abilities may be used, but at one level lower: a master may use the adept level of the ability through the transcendental weapon; an adept may use the novice level. A novice cannot use the ability together with a transcendental weapon.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Witch Braid": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 800,
    category: "treasure",
    effect: [
      "This braid is made from three raritys of hair or fur and keeps death at bay, giving a +1 bonus to Strong during death tests. Non-player characters with the braid get to make death tests, with the +1 bonus.",
    ],
    bulk: false,
    slot: 0,
    max_durability: 0,
  },
  "Primal Pivot": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 2300,
    category: "treasure",
    effect: ["Let a player swap the value of two stats."],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
  "Primal Focus": {
    roll: [],
    quality: [],
    rarity: "artifact",
    cost: 2300,
    category: "treasure",
    effect: [
      "Using the Primal Focus allows a player to choose one of the following options: either forget an ability and regain its full XP value, or swap the base values of two stats.",
    ],
    bulk: true,
    slot: 0,
    max_durability: 0,
  },
};
