import { ItemStatic } from "../../Types";

export const weapons_content: Record<string, ItemStatic> = {
  Knuckles: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 4,
      },
    ],
    quality: ["Short"],
    rarity: "normal",
    cost: 0,
    category: "natural weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  Tusks: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 4,
      },
    ],
    quality: ["Short"],
    rarity: "normal",
    cost: 0,
    category: "natural weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Sharp Claws": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Short"],
    rarity: "normal",
    cost: 0,
    category: "natural weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  Claws: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 4,
      },
    ],
    quality: ["Short"],
    rarity: "normal",
    cost: 0,
    category: "natural weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  Bite: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 4,
      },
    ],
    quality: ["Short"],
    rarity: "normal",
    cost: 0,
    category: "natural weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Long Claws": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 4,
      },
    ],
    quality: ["Long"],
    rarity: "normal",
    cost: 0,
    category: "natural weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Wraith Claws": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: [],
    rarity: "normal",
    cost: 0,
    category: "natural weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 10,
  },
  Dagger: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Short"],
    rarity: "normal",
    cost: 100,
    category: "short weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  Dirk: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Short"],
    rarity: "normal",
    cost: 100,
    category: "short weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  Knife: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Short"],
    rarity: "normal",
    cost: 100,
    category: "short weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  Sword: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: [],
    rarity: "normal",
    cost: 500,
    category: "one-hand weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  Axe: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: [],
    rarity: "normal",
    cost: 500,
    category: "one-hand weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  Mace: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: [],
    rarity: "normal",
    cost: 500,
    category: "one-hand weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  Spear: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Long"],
    rarity: "normal",
    cost: 300,
    category: "long weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 8,
  },
  Greatsword: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Long"],
    rarity: "normal",
    cost: 1000,
    category: "long weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 10,
  },
  Greatsaxe: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Long"],
    rarity: "normal",
    cost: 1000,
    category: "long weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 10,
  },
  Maul: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Long"],
    rarity: "normal",
    cost: 1000,
    category: "long weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 10,
  },
  "Bastard Sword": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Bastard"],
    rarity: "quality",
    cost: 5000,
    category: "one-hand weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Fencing Sword": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Precise"],
    rarity: "quality",
    cost: 2500,
    category: "one-hand weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Balanced Blade": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Balanced 1"],
    rarity: "quality",
    cost: 2500,
    category: "one-hand weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Crow's Beak": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Impact"],
    rarity: "quality",
    cost: 2500,
    category: "one-hand weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  Lance: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Bastard", "Long"],
    rarity: "quality",
    cost: 1500,
    category: "long weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  Flail: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Jointed"],
    rarity: "quality",
    cost: 2500,
    category: "one-hand weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Long-hammer": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Bastard", "Unwieldy"],
    rarity: "quality",
    cost: 5000,
    category: "one-hand weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Long-Whip": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Jointed", "Ensnaring", "Blunt"],
    rarity: "quality",
    cost: 1000,
    category: "short weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  Estoc: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Impact"],
    rarity: "quality",
    cost: 2500,
    category: "one-hand weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Assassin's Blade": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Short", "Concealed"],
    rarity: "normal",
    cost: 500,
    category: "short weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  "Parrying Dagger": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Short", "Balanced 1"],
    rarity: "normal",
    cost: 500,
    category: "short weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  Stiletto: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Short", "Impact"],
    rarity: "normal",
    cost: 500,
    category: "short weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 6,
  },
  Halberd: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Long", "Impact"],
    rarity: "quality",
    cost: 1500,
    category: "long weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 8,
  },
  Pike: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Long", "Precise"],
    rarity: "quality",
    cost: 1500,
    category: "long weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 8,
  },
  "Sturdy Staff": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Long", "Blunt"],
    rarity: "normal",
    cost: 10,
    category: "long weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 6,
  },
  "Wooden Staff": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Long", "Blunt"],
    rarity: "normal",
    cost: 10,
    category: "long weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 6,
  },
  Quarterstaff: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 6,
      },
    ],
    quality: ["Long", "Blunt"],
    rarity: "normal",
    cost: 10,
    category: "long weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 6,
  },
  "Chain Staff": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Long", "Ensnaring"],
    rarity: "quality",
    cost: 1500,
    category: "long weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 8,
  },
  "Battle Claw": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 4,
      },
    ],
    quality: ["Short", "Impact"],
    rarity: "quality",
    cost: 100,
    category: "short weapon",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  Shield: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 4,
      },
    ],
    quality: ["Short", "Balanced 1"],
    rarity: "quality",
    cost: 300,
    category: "shield",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  Buckler: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 4,
      },
    ],
    quality: ["Short", "Flexible", "Balanced 1"],
    rarity: "quality",
    cost: 1500,
    category: "shield",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Steel Shield": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 4,
      },
    ],
    quality: ["Short", "Balanced 2"],
    rarity: "quality",
    cost: 1500,
    category: "shield",
    effect: [],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Double-axe": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Impact"],
    rarity: "quality",
    cost: 5000,
    category: "heavy weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 10,
  },
  "Battle Flail": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Jointed"],
    rarity: "quality",
    cost: 5000,
    category: "heavy weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 10,
  },
  "Executioner's Axe": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Impact", "Massive", "Unwieldy"],
    rarity: "mystical",
    cost: 5000,
    category: "heavy weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 10,
  },
  Warhammer: {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Blood-letting", "Massive", "Unwieldy"],
    rarity: "mystical",
    cost: 5000,
    category: "heavy weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 10,
  },
  "Executioner's Sword": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Precise", "Massive", "Unwieldy"],
    rarity: "mystical",
    cost: 5000,
    category: "heavy weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 10,
  },
  "Heavy Flail": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Jointed", "Massive", "Unwieldy"],
    rarity: "mystical",
    cost: 5000,
    category: "heavy weapon",
    effect: [],
    bulk: false,
    slot: 2,
    max_durability: 10,
  },
  "Right Hand of Kraghammer": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Massive", "Impact"],
    rarity: "unique",
    cost: 5000,
    category: "one-hand weapon",
    effect: [
      "-2 to movement speed.",
      "+2 to Vigilant Modifier.",
      "The Right Hand of Kraghammer can damage targets with Spirit Form.",
    ],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "Left Hand of Kraghammer": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 8,
      },
    ],
    quality: ["Massive", "Precise"],
    rarity: "unique",
    cost: 5000,
    category: "one-hand weapon",
    effect: [
      "-2 to movement speed.",
      "If a target has been hit by the Right Hand of Kraghammer, the Left Hand of Kraghammer deals an additional 1d4 damage.",
      "The Left Hand of Kraghammer can damage targets with the ability Spirit Form.",
    ],
    bulk: false,
    slot: 1,
    max_durability: 8,
  },
  "King's Traitor": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 4,
      },
    ],
    quality: ["Short"],
    rarity: "unique",
    cost: 5000,
    category: "one-hand weapon",
    effect: [
      "As an action and by passing [Attack or Casting - Defense], this weapon sends out a spectral slash dealing d4 damage. This attack can harm celestial creatures",
      "As a free action and at the cost of 1d4 temporary corruption, the weapon can be passed on to a different target - no direct contact is required.",
      "Each successful attack on a celestial creature will give the wielder of this weapon 1 level of the effect Traitor's Mark.",
    ],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Wolfbane Torch": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 4,
      },
    ],
    quality: [],
    rarity: "unique",
    cost: 5000,
    category: "one-hand weapon",
    effect: [
      "As an Action and at the cost of 1d4 temporary corruption. A burst of fire launches from the torch setting 1 tile on fire.",
      "As an Action and at the cost of 1d4 temporary corruption. A burning tile can be expanding by 1 tile in radius.",
      "A burning tile deal d8 damage, and obscure line of sight.",
    ],
    bulk: false,
    slot: 1,
    max_durability: 4,
  },
  "Ebonfang Warspear": {
    roll: [
      {
        source: "base",
        type: "damage",
        value: 10,
      },
    ],
    quality: ["Long", "Precise"],
    rarity: "unique",
    cost: 5000,
    category: "long weapon",
    effect: [
      "+2 Accurate Modifier",
      "Deal 1 damage to all enemies on each succesful hit - ignoring armor.",
    ],
    bulk: false,
    slot: 2,
    max_durability: 10,
  },
};
