import { EffectStatic } from "../../Types";

export const effects_content: Record<string, EffectStatic> = {
  "Traitor's Mark": {
    description:
      "If damage is dealt to a celestial creatingure, you receive damage equal to the level of this effect - ignoring armor. You can lower this effect by 1 level through sacrificing 1d12 thaler to the celeatingial being as an offering.",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    reset: "sleeping",
    category: "effect",
  },
  Starving: {
    description: "Decreases all base stats by 1.",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    reset: "eating",
    category: "effect",
  },
  Overburdened: {
    description:
      "Decreases the stat modifier of attack, defense, accurate, quick, discreet and strong by",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    reset: "never",
    category: "effect",
  },
  Focused: {
    description: "Roll twice and pick the highest result.",
    base_amount: 0,
    level_amount: 0,
    type: "positive",
    reset: "roll",
    category: "effect",
  },
  Unfocused: {
    description: "Roll twice and pick the lowest result.",
    base_amount: 0,
    level_amount: 0,
    type: "negative",
    reset: "roll",
    category: "effect",
  },
  "Weakened Cunning": {
    description: "Decreases cunning base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    reset: "sleeping",
    category: "effect",
  },
  "Weakened Discreet": {
    description: "Decreases discreet base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    reset: "sleeping",
    category: "effect",
  },
  "Weakened Persuasive": {
    description: "Decreases persuasive base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    reset: "sleeping",
    category: "effect",
  },
  "Weakened Quick": {
    description: "Decreases quick base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    reset: "sleeping",
    category: "effect",
  },
  "Weakened Resolute": {
    description: "Decreases resolute base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    reset: "sleeping",
    category: "effect",
  },
  "Weakened Strong": {
    description: "Decreases strong base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    reset: "sleeping",
    category: "effect",
  },
  "Weakened Vigilant": {
    description: "Decreases vigilant base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    reset: "sleeping",
    category: "effect",
  },
  "Weakened Accurate": {
    description: "Decreases accurate base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    reset: "sleeping",
    category: "effect",
  },
  "Enhanced Cunning": {
    description: "Increases cunning base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    reset: "sleeping",
    category: "effect",
  },
  "Enhanced Discreet": {
    description: "Increases discreet base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    reset: "sleeping",
    category: "effect",
  },
  "Enhanced Persuasive": {
    description: "Increases persuasive base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    reset: "sleeping",
    category: "effect",
  },
  "Enhanced Quick": {
    description: "Increases quick base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    reset: "sleeping",
    category: "effect",
  },
  "Enhanced Resolute": {
    description: "Increases resolute base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    reset: "sleeping",
    category: "effect",
  },
  "Enhanced Strong": {
    description: "Increases strong base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    reset: "sleeping",
    category: "effect",
  },
  "Enhanced Vigilant": {
    description: "Increases vigilant base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    reset: "sleeping",
    category: "effect",
  },
  "Enhanced Accurate": {
    description: "Increases accurate base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    reset: "sleeping",
    category: "effect",
  },
  Theurgy: {
    description: "Increases theurgy mystical powers rolls by",
    base_amount: 5,
    level_amount: 0,
    type: "positive",
    reset: "never",
    category: "effect",
  },
  "Blessed Shield": {
    description: "Increases armor roll by",
    base_amount: 5,
    level_amount: 2,
    type: "positive",
    reset: "sleeping",
    category: "effect",
  },
  "Witch Hammer": {
    description: "Increases the damage roll by",
    base_amount: 5,
    level_amount: 0,
    type: "positive",
    reset: "sleeping",
    category: "effect",
  },
  "Witch Hammer Undead": {
    description: "Increases the damage roll against undead/abominations by",
    base_amount: 7,
    level_amount: 2,
    type: "positive",
    reset: "sleeping",
    category: "effect",
  },
  "Iron Fist": {
    description: "Increases damage roll by",
    base_amount: 5,
    level_amount: 0,
    type: "positive",
    reset: "damage",
    category: "effect",
  },
  "Hunter's Instinct": {
    description: "Two chances to hit on all ranged attacks.",
    base_amount: 0,
    level_amount: 0,
    type: "positive",
    reset: "never",
    category: "effect",
  },
  Flanking: {
    description: "Increases damage roll by 4, and the attack modifier by +2.",
    base_amount: 0,
    level_amount: 0,
    type: "positive",
    reset: "never",
    category: "effect",
  },
  Flanked: {
    description: "Decreases armor roll by 4, and the defense modifier by -2.",
    base_amount: 0,
    level_amount: 0,
    type: "negative",
    reset: "never",
    category: "effect",
  },
  "Critical Strike": {
    description: "Increases damage roll by 6.",
    base_amount: 0,
    level_amount: 0,
    type: "positive",
    reset: "damage",
    category: "effect",
  },
  Starvation: {
    description:
      "Each level of starvation decreases all base stats by 1. If a stat reaches 0 the character dies.",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    reset: "eating",
    category: "effect",
  },
};
