import { EffectStatic } from "../../Types";

export const effects_content: Record<string, EffectStatic> = {
  Cunning: {
    description: "Modify cunning base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    category: "effect",
  },
  Discreet: {
    description: "Modify discreet base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    category: "effect",
  },
  Persuasive: {
    description: "Modify persuasive base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    category: "effect",
  },
  Quick: {
    description: "Modify quick base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    category: "effect",
  },
  Resolute: {
    description: "Modify resolute base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    category: "effect",
  },
  Strong: {
    description: "Modify strong base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    category: "effect",
  },
  Vigilant: {
    description: "Modify vigilant base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    category: "effect",
  },
  Accurate: {
    description: "Modify accurate base stat by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",

    category: "effect",
  },
  Damage: {
    description: "Modify damage roll by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    category: "effect",
  },
  Armor: {
    description: "Modify armor roll by",
    base_amount: 1,
    level_amount: 1,
    type: "positive",
    category: "effect",
  },
  Starving: {
    description: "Decreases all base stats by",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    category: "effect",
  },
  Overburdened: {
    description:
      "Decreases the stat modifier of attack, defense, accurate, quick, discreet and strong by",
    base_amount: 1,
    level_amount: 1,
    type: "negative",
    category: "effect",
  },
  Focused: {
    description: "Roll twice and pick the highest result.",
    base_amount: 0,
    level_amount: 0,
    type: "positive",
    category: "rules effect",
  },
  Unfocused: {
    description: "Roll twice and pick the lowest result.",
    base_amount: 0,
    level_amount: 0,
    type: "negative",
    category: "rules effect",
  },
  Flanking: {
    description: "Modify damage roll by +4, and the attack modifier by +2.",
    base_amount: 0,
    level_amount: 0,
    type: "positive",
    category: "rules effect",
  },
  Flanked: {
    description: "Decreases armor roll by -4, and the defense modifier by -2.",
    base_amount: 0,
    level_amount: 0,
    type: "negative",
    category: "rules effect",
  },
};
